### ISSUE TITLE
Improve expressions

### ISSUE THREAD

**Issue by TechMagister** [amberframework/liquid.cr#5]
- [ ] Add `contains` keyword ( http://shopify.github.io/liquid/basics/operators/ )
- [ ] Add support for Array into expressions
- [ ] Add square bracket [ ] notation to access an element

**Comment by hugopl** [comment]
I think it's possible to use the [stack machine introduced in the Drop implementation](https://github.com/TechMagister/liquid.cr/pull/56/files#diff-d2ff13ede4528e61a50f0a5f35f043f5438e7f83aae05cc285bf5f079def8e6a) to fix that.
