### ISSUE TITLE
Iterations create blank lines

### ISSUE THREAD

**Issue by HCLarsen** [amberframework/liquid.cr#81]
When there's an iterator in the liquid template, the parser introduces a carriage return at the beginning of each iteration, and another one at the end, leaving a blank line between each iteration. 

This does appear to be known, since it's accounted for in template_spec.cr:

```
  it "should render for loop with loop variable" do
    tpl = Parser.parse("{% for x in 0..2 %}
    Iteration n°{{ forloop.index }}
    {% endfor %}")
    tpl.render(Context.new(:strict)).should eq "\n    Iteration n°1\n    \n    Iteration n°2\n    \n    Iteration n°3\n    "
  end
```

However, this isn't desirable behaviour to me, and I'm wondering if anyone else agrees that we should change this, or if it's preferred to leave it as is.

**Comment by hugopl** [comment]
This behavior matches with the Ruby version of LiquidTemplate, and this is desired.

```
2.7.6 :004"> Liquid::Template.parse("{% for x in (0..2) %}
2.7.6 :005">   Iteration n°{{ forloop.index }}
2.7.6 :006 >   {% endfor %}").render
 => "\n  Iteration n°1\n  \n  Iteration n°2\n  \n  Iteration n°3\n  " 
```

Note that ruby version requires the parenthesis in the range, Crystal version not.
